### ISSUE TITLE
M1Macだと起動できないです。

### ISSUE THREAD

**Issue by ShrkSoft** [Axeryok/CocoaInput#28]
M1CPU用のJava(Azul Systemsが提供しているJava)だと、
Cocoainput encountered an error during the common_setup event phase
java.lang.NoClassDefFoundError: Could not initialize class com.sun.jna.Native
と表示され、タイトル画面に到達できません。
以下クラッシュレポートです。
```
java.lang.NoClassDefFoundError: Could not initialize class com.sun.jna.Native
Stacktrace:
	at jp.axer.cocoainput.arch.darwin.Handle.<clinit>(Handle.java:9) ~[cocoainput:4.0.3] {re:classloading}
	at jp.axer.cocoainput.arch.darwin.DarwinController.<init>(DarwinController.java:15) ~[cocoainput:4.0.3] {re:classloading}
	at jp.axer.cocoainput.CocoaInput.<init>(CocoaInput.java:33) ~[cocoainput:4.0.3] {re:classloading}
	at jp.axer.cocoainput.loader.ForgeLoader.setup(ForgeLoader.java:23) ~[cocoainput:4.0.3] {re:classloading}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:247) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:239) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:120) ~[forge:36.2] {re:classloading}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:121) ~[forge:?] {re:classloading}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(Unknown Source) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:?] {}
```

**Comment by Ostrichbeta** [comment]
Check this version, I applied this PR (https://github.com/Axeryok/CocoaInput/pull/25), applied this patch (https://github.com/nakanotti/CocoaInput/), and recompiled the mod, I've tested it in 1.19 on M2 Mac and it runs well.
[CocoaInput-1.19-fabric-4.0.5.jar.zip](https://github.com/Axeryok/CocoaInput/files/9160886/CocoaInput-1.19-fabric-4.0.5.jar.zip)

**Comment by exkuretrol** [comment]
> Check this version, I applied this PR (#25), applied this patch (https://github.com/nakanotti/CocoaInput/), and recompiled the mod, I've tested it in 1.19 on M2 Mac and it runs well. [CocoaInput-1.19-fabric-4.0.5.jar.zip](https://github.com/Axeryok/CocoaInput/files/9160886/CocoaInput-1.19-fabric-4.0.5.jar.zip)

Thank you, I have test in 1.19.2 on My M1 Mac, and it work properly!
